sudo: true

language: python
python:
   - "2.7"

services:
   - redis-server

before_script:
   - echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
   - sudo apt-get update
   - sudo apt-get install mongodb-org-server mongodb-org -y
   - sudo service mongod start
   - sleep 15 #https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
   - mongo --eval "printjson(db.serverStatus())"
   - mongo --eval 'db.adminCommand({setParameter:true, textSearchEnabled:true})' #http://stackoverflow.com/a/20673005/3448851


install:
   - pip install tox-travis

script:
   - mongo --version
   - tox