sudo: true

language: python
python:
   - "2.7"

services:
   - docker
   - redis-server
   - mongodb

before_install:
   - docker pull ubuntu
   - docker run ubuntu

install :
   - sudo apt-get install
   - pip install -r requirements/requirements-prod.txt
   - pip install -r requirements/requirements-test.txt

script:
   - coverage run runtests.py

after_success:
   - codecov
