sudo: true

language: python
python:
   - "2.7"

services:
   - docker

before_install:
   - docker pull ubuntu
   - docker run ubuntu

install :
   - sudo apt-get install
   - pip install -r requirements/requirements-prod.txt
   - pip install -r requirements/requirements-test.txt

script:
   - tox

after_success:
  - codecov
