sudo: true

language: python
python:
   - "2.7"

services:
   - redis-server


before_install:
   - echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb.list
   - sudo apt-get update
   - sudo apt-get install mongodb-org-server=3.4
   - sleep 15 #https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections

install:
   - pip install tox-travis

before_script:
   - mongo --version


script:
   - tox

