sudo: true

language: python
python:
   - "2.7"

services:
   - redis-server
   - mongodb

before_script:
  - sleep 15 #https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections

install:
   - pip install tox-travis

script:
   - mongo --version
   - tox

