sudo: true

language: python
python:
   - "2.7"

services:
   - docker

before_install:
   - docker pull mongo:3.4
   - docker run mongo:3.4 -d
   - sleep 5
   - mongo --eval "printjson(db.serverStatus())"
   - mongo --eval 'db.adminCommand({setParameter:true, textSearchEnabled:true})' #http://stackoverflow.com/a/20673005/3448851
   - docker pull redis:3.2
   - docker run redis:3.2 -d


install:
   - pip install tox-travis

script:
   - mongo --version
   - tox