sudo: true

language: python
python:
   - "2.7"


services:
   - docker


before_install:
   - docker pull mongo:latest
   - docker run -p 27017:27017 -d mongo
   - sleep 5
   - mongo --eval "printjson(db.serverStatus())"
   - mongo --eval 'db.adminCommand({setParameter:true, textSearchEnabled:true})' #http://stackoverflow.com/a/20673005/3448851
   - docker pull redis:latest
   - docker run -d redis

cache: pip

install:
   - pip install tox-travis
   - pip install codecov

script:
   - mongo --version
   - tox
   - if [ ${TRAVIS} ]; then  codecov -t "9b11cbf9-6fba-45d9-8773-847875dfd8b5";  fi
