# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=400)),
                ('journal_title', models.CharField(db_index=True, max_length=120)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('pub_year', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('pmid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='keywords',
            field=models.ManyToManyField(to='journals.PublicationKeyword'),
        ),
        migrations.AddField(
            model_name='journal',
            name='pub_type',
            field=models.ManyToManyField(to='journals.PublicationType'),
        ),
    ]
