# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='category',
            field=models.CharField(choices=[('blog', 'Blog'), ('website', 'Website'), ('journal', 'Journal'), ('book', 'Book'), ('doc', 'Documentation'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='journal',
            name='entry_created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='journal',
            name='entry_updated_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='image',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='pub_date_unformated',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='publicationkeyword',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='publicationtype',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
